"""Generate the flight data and flight event reference pages of the documentation.

The tables list every ``FlightDataType`` and ``FlightEvent`` member with the name, symbol and SI unit
that OpenRocket gives it, and the OpenRocket versions it exists in. They are read from real OpenRocket
jars, so this needs a jar per version (one JVM per process, hence one subprocess per jar).

Usage (from the repository root):

    python tools/generate_reference.py 22.02=/path/OpenRocket-22.02.jar 23.09=... 24.12=... 26.xx=...

Order the arguments from the oldest to the newest version: names and units are taken from the newest
version that has the member. Re-run this when a new OpenRocket version is supported; the output goes to
``docs/reference/flight-data.md`` and ``docs/reference/flight-events.md``.
"""
import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))  # use the checkout, even if orhelper is not installed
OUTPUT = ROOT / "docs" / "reference"


def dump(jar, destination):
    """Runs in a subprocess: read the variables and events of one OpenRocket jar into a JSON file."""
    import orhelper

    with orhelper.OpenRocketInstance(jar=jar, log_level="ERROR", jvm_args=["-Djava.awt.headless=true"]) as instance:
        helper = orhelper.Helper(instance)
        data = {}
        for member in orhelper.FlightDataType:
            try:
                java = helper.translate_flight_data_type(member)
            except AttributeError:
                continue
            group = java.getUnitGroup()
            data[member.name] = {
                "name": str(java.getName()),
                "symbol": str(java.getSymbol()),
                "unit": str(group.getSIUnit().getUnit()),
            }
        java_events = {str(e.name()): str(e.toString()) for e in instance.openrocket_core.simulation.FlightEvent.Type.values()}
        events = {m.name: java_events[m.name] for m in orhelper.FlightEvent if m.name in java_events}
    Path(destination).write_text(json.dumps({"data": data, "events": events}))


def escape(text):
    return text.replace("|", "\\|")


def table(rows, header):
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


def unit_cell(member, versions, results):
    """The SI unit of a variable; spelled out per version if it differs between versions."""
    by_unit = {}
    for version in versions:
        info = results[version]["data"].get(member)
        if info:
            unit = info["unit"].replace("\u200b", "").strip() or "–"  # OpenRocket uses a zero-width space for "none"
            by_unit.setdefault(unit, []).append(version)
    if len(by_unit) == 1:
        return escape(next(iter(by_unit)))
    return "<br>".join(f"{escape(unit)} ({', '.join(vs)})" for unit, vs in by_unit.items())


def availability(present, versions):
    return "all" if len(present) == len(versions) else ", ".join(v for v in versions if v in present)


def main(arguments):
    jars = dict(argument.split("=", 1) for argument in arguments)
    versions = list(jars)
    results = {}
    with tempfile.TemporaryDirectory() as directory:
        for version, jar in jars.items():
            destination = Path(directory) / f"{version}.json"
            subprocess.run([sys.executable, __file__, "--dump", jar, str(destination)], check=True, cwd=ROOT)
            results[version] = json.loads(destination.read_text())

    import orhelper  # only for the member order

    list_versions = ", ".join(versions)
    note = (f"<!-- Generated by tools/generate_reference.py from OpenRocket {list_versions}. Do not edit by hand. -->\n")

    rows = []
    for member in orhelper.FlightDataType:
        present = [v for v in versions if member.name in results[v]["data"]]
        if not present:
            continue
        info = results[present[-1]]["data"][member.name]
        rows.append([f"`{member.name}`", escape(info["name"]), f"`{escape(info['symbol'])}`", unit_cell(member.name, versions, results),
                     availability(present, versions)])
    (OUTPUT / "flight-data.md").write_text(
        note + FLIGHT_DATA_INTRO + table(rows, ["Member", "Name in OpenRocket", "Symbol", "Unit (SI)", "Available in"]) + "\n")

    rows = []
    for member in orhelper.FlightEvent:
        present = [v for v in versions if member.name in results[v]["events"]]
        if not present:
            continue
        rows.append([f"`{member.name}`", escape(results[present[-1]]["events"][member.name]), availability(present, versions)])
    (OUTPUT / "flight-events.md").write_text(
        note + FLIGHT_EVENTS_INTRO + table(rows, ["Member", "Name in OpenRocket", "Available in"]) + "\n")
    print(f"Wrote {len(rows)} events and the flight data table for {list_versions}")


FLIGHT_DATA_INTRO = """# Flight data variables

`orhelper.FlightDataType` has one member for each variable that OpenRocket records during a simulation.
Pass members (or their names as strings) to
[`Helper.get_timeseries`][orhelper.Helper.get_timeseries] and
[`Helper.get_final_values`][orhelper.Helper.get_final_values].

!!! info "Units"
    Values are returned in **SI units** (metres, kilograms, seconds, radians), whatever unit
    OpenRocket shows in its user interface. For example, `TYPE_MOTOR_MASS` is in kg and
    `TYPE_ROLL_RATE` is in rad/s. The *Unit (SI)* column gives the unit of each variable.

!!! warning "Latitude and longitude changed unit in OpenRocket 24.12"
    `TYPE_LATITUDE` and `TYPE_LONGITUDE` are in **radians** in OpenRocket 22.02 and 23.09, but in
    **degrees** in 24.12 and later. The same simulation gives `0.7854` for a launch site at 45°N in
    22.02/23.09 and `45.0` in 24.12 and later, with no error. Check the version you use, or convert
    with `numpy.degrees` when the values are small.

A variable that doesn't exist in the OpenRocket version you run raises an `AttributeError` when you
request it; the last column shows where each is available. `TYPE_PROPELLANT_MASS` is a legacy name of
`TYPE_MOTOR_MASS`, and either can be used with any version. Some variables are `nan` at some time steps,
for example at the first one; use `numpy.nanmax` and friends.

"""

FLIGHT_EVENTS_INTRO = """# Flight events

`orhelper.FlightEvent` has one member for each kind of event OpenRocket records during a flight.
[`Helper.get_events`][orhelper.Helper.get_events] returns a dictionary that maps each event that occurred
to the list of times (in seconds) at which it did.

"""

if __name__ == "__main__":
    if len(sys.argv) == 4 and sys.argv[1] == "--dump":
        dump(sys.argv[2], sys.argv[3])
    elif len(sys.argv) > 1:
        main(sys.argv[1:])
    else:
        sys.exit(__doc__)
